# Generated by Django 6.0.4 on 2026-04-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'code', 'is_used'], name='accounts_ot_phone_c59299_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx'),
        ),
        migrations.AlterModelTable(
            name='otp',
            table='accounts_otp',
        ),
    ]
