# Generated by Django 6.0.4 on 2026-05-05 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_is_deleted_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان گروه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='عکس گروه')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخرین پیام')),
                ('last_message_preview', models.CharField(blank=True, max_length=100, verbose_name='پیش\u200cنمایش آخرین پیام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'گفتگوی گروهی',
                'verbose_name_plural': 'گفتگوهای گروهی',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر'), ('moderator', 'مدیریت'), ('member', 'عضو')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده توسط همه؟')),
            ],
            options={
                'verbose_name': 'پیام گروهی',
                'verbose_name_plural': 'پیام\u200cهای گروهی',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_convers_516edb_idx',
        ),
        migrations.AddField(
            model_name='groupconversation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_groups', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه'),
        ),
        migrations.AddField(
            model_name='groupconversation',
            name='members',
            field=models.ManyToManyField(related_name='group_conversations', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.groupconversation'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.groupconversation', verbose_name='گفتگو'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='خوانده شده توسط'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
