# Generated by Django 5.2.13 on 2026-05-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_alter_follow_options_alter_follow_follower_and_more'),
    ]

    operations = [
    ]
