# Generated by Django 5.2.13 on 2026-05-12 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0012_savedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('interaction_type', models.CharField(max_length=20)),
                ('interaction_weight', models.FloatField(default=1.0)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_with_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'target_user', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='UserPostEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration_ms', models.IntegerField(blank=True, help_text='مدت زمان نگاه کردن به پست به میلی\u200cثانیه', null=True)),
                ('scroll_depth', models.IntegerField(default=0, help_text='درصد اسکرول شده (0-100)')),
                ('visibility_ratio', models.FloatField(default=1.0, help_text='نسبت زمانی که پست در viewport بوده')),
                ('liked_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('commented_at', models.DateTimeField(blank=True, null=True)),
                ('attention_index', models.FloatField(default=0.0, help_text='نمره توجه بر اساس Z-Score')),
                ('engagement_depth', models.FloatField(default=0.0, help_text='عمق تعامل (لایک، ذخیره، اشتراک)')),
                ('total_value_score', models.FloatField(default=0.0, help_text='وزن نهایی پست برای این کاربر')),
                ('is_outlier', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_engagements', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-total_value_score'], name='interaction_user_id_c2253f_idx'), models.Index(fields=['post', '-total_value_score'], name='interaction_post_id_480883_idx'), models.Index(fields=['user', '-created_at'], name='interaction_user_id_435143_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
