# Generated by Django 5.2.13 on 2026-04-12 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['-usage_count'], name='hashtags_ha_usage_c_d69b9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='hashtags.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'hashtag')},
            },
        ),
    ]
