# Generated by Django 5.2.13 on 2026-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
