# Generated by Django 5.2.13 on 2026-04-15 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL, verbose_name='bloke object')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users_set', to=settings.AUTH_USER_MODEL, verbose_name='bloke')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloks',
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='blocks_bloc_blocker_43a3a7_idx'), models.Index(fields=['blocked', '-created_at'], name='blocks_bloc_blocked_37402b_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
