"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l&%20%-jdu!y^g04zw3ru#r6)t-@)i2jahs$sys-o8m0(ret=n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []





INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.accounts',
    'apps.profiles',
    'apps.posts',
    'apps.interactions',
    'apps.follows',
    'apps.stories',
    'apps.messaging',
    'apps.hashtags',
    'apps.blocks',
    'apps.ml',
    'django_celery_results',
    'django_celery_beat',
    'apps.search',
    #"drf-spectacular"
    'drf_spectacular',
    'corsheaders'

]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]






TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]



STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_DIRS = [
    BASE_DIR / "static",
]




WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Note the closing quote and comma
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#pstgresql 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',hggj
#         'USER': 'postgres',
#         'PASSWORD': '123456',
#         'HOST': '192.168.1.110',
#         'PORT': '5432',
#     }
# }

#sql server for connection in vm
# DATABASES = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'DjangoDB',
#         'USER': 'DjangoUser',
#         'PASSWORD': 'Django@2024#Strong',
#         'HOST': '192.168.1.2000',
#         'PORT': '1433',
#         'OPTIONS': {
#             'driver': 'SQL Server Native Client 11.0',  
#             'MARS_Connection': 'Yes',
#             'ExtraParams': 'TrustServerCertificate=yes',
#         },
#     }
# }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'
#SMS_PROVIDER = 'kavenegar' 
#KAVENEGAR_API_KEY = 'YOUR_API_KEY_HERE'
SMS_SENDER = '10008663'
SMS_PROVIDER = 'fake'  


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}





SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}




  
# OLLAMA_BASE_URL = 'http://localhost:11434'
# OLLAMA_MODEL = 'gemma3:27b'
# ML_FEATURES = {
#     'ENABLE_RECOMMENDATION': True,
#     'ENABLE_MODERATION': True,
#     'ENABLE_SENTIMENT': False,
#     'AUTO_RETRAIN': True,  
#     'RETRAIN_INTERVAL_DAYS': 7,
# }

#INSTALLED_APPS += ['apps.ml']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


OLLAMA_BASE_URL = 'http://localhost:11434'
OLLAMA_MODEL = 'gemma3:27b'  
ML_FEATURES = {
    'ENABLE_RECOMMENDATION': True,
    'ENABLE_MODERATION': True,
    'ENABLE_SENTIMENT': False,
    'AUTO_RETRAIN': True,  
    'RETRAIN_INTERVAL_DAYS': 7,
}

PERSONALITY_ANALYSIS_USE_AI = True 


CELERY_BROKER_URL = 'django://'   
CELERY_RESULT_BACKEND = 'django-db'  
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BROKER_TRANSPORT = 'django'






KAVENEGAR_API_KEY = '4D706439326650596F41677543517261356B6A614142663053775846754D764D41474F424C69386E586D6B3D'
SMS_SENDER = '2000660110'
#SMS_PROVIDER = 'kavenegar' 

SIMPLE_JWT = {
    
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),      
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

}

SEARCH_USE_OLLAMA = True  
SEARCH_OLLAMA_TIMEOUT = 30
OLLAMA_ENABLED = True






CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",   # Live Server
    "http://localhost:5500",
    "http://127.0.0.1:3000",  
]




CORS_ALLOW_ALL_ORIGINS = True  
CORS_ALLOW_CREDENTIALS = True
