# Generated by Django 6.0.4 on 2026-04-22 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('moderation', 'داده تعدیل محتوا'), ('interaction', 'داده تعامل کاربر'), ('sentiment', 'داده احساسات'), ('custom', 'داده سفارشی')], max_length=50)),
                ('source_table', models.CharField(max_length=100)),
                ('features', models.JSONField()),
                ('labels', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField()),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('is_validated', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('recommendation', 'موتور پیشنهاد'), ('moderation', 'تعدیل محتوا'), ('sentiment', 'تحلیل احساسات'), ('trending', 'پیش\u200cبینی ترند')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('training', 'در حال آموزش'), ('active', 'فعال'), ('failed', 'خطا'), ('deprecated', 'منسوخ')], default='pending', max_length=20)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('trained_samples', models.IntegerField(default=0)),
                ('training_duration', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_type', 'status'], name='ml_mlmodelr_model_t_068352_idx'), models.Index(fields=['-trained_at'], name='ml_mlmodelr_trained_1be01f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('input_hash', models.CharField(max_length=64)),
                ('prediction_result', models.JSONField()),
                ('confidence', models.FloatField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='ml_predicti_cache_k_ee30d9_idx'), models.Index(fields=['model_type', '-hit_count'], name='ml_predicti_model_t_636a13_idx'), models.Index(fields=['expires_at'], name='ml_predicti_expires_4ef825_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('embedding_vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.JSONField(default=list)),
                ('activity_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_embedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-activity_score'], name='ml_userembe_activit_a66704_idx')],
            },
        ),
    ]
