# Generated by Django 5.1.6 on 2026-04-27 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_file_name_post_file_size_alter_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='posts/media/%Y/%m/%d/', verbose_name='فایل')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو'), ('audio', 'صوت'), ('document', 'سند'), ('other', 'سایر')], default='image', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='ترتیب نمایش فایل\u200cها')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
            options={
                'verbose_name': 'رسانه پست',
                'verbose_name_plural': 'رسانه\u200cهای پست',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
