# Generated by Django 5.1.6 on 2026-04-27 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_file_post_file_name_post_file_size_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='posts/media/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('file', 'فایل')], db_index=True, max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'file_type'], name='posts_postm_post_id_85f59a_idx'), models.Index(fields=['post', 'order'], name='posts_postm_post_id_857b22_idx')],
            },
        ),
    ]
