# Generated by Django 5.2.13 on 2026-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Video file for the post (MP4, MOV, etc.)', null=True, upload_to='posts/videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for the video', null=True, upload_to='posts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], db_index=True, max_length=10),
        ),
    ]
